<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tobot">

  <!-- Constant for the xacro model -->

  <xacro:property name="GROUND_CLEARANCE" value="0.2" />
  <xacro:property name="width" value="0.285" />
  <xacro:property name="bodylen" value="0.355" />
  <xacro:property name="wheel_w" value="0.039" />
  <xacro:property name="wheel_rad" value="0.075" />
  <xacro:property name="plat_rad" value="0.285" />
  <xacro:property name="plat_len" value="0.005" />
  <xacro:property name="HIGH_PLATFORM" value="0.15" />
  <xacro:property name="posz_laser" value="0.285" />
  <xacro:property name="posz_camera" value="0.5" />
  <xacro:property name="fwheel_rad" value="0.0325" />
  <xacro:property name="radar_w" value="0.2" />
  <xacro:property name="radar_rad" value="0.1" />
  <xacro:property name="radar_up_baselink" value="0.3" />
  <xacro:property name="PI" value="3.1415" />
   
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  
  <material name="red">
    <color rgba="1 0 0 1"/> 
  </material>


  <!-- Actual frame and materials -->

<!--  <link name="base_link">
    <visual>
      <geometry>
         <cylinder length="${bodylen}" radius="${width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${GROUND_CLEARANCE}"/>
      <material name="blue">
        <color rgba="0 0.2 0.4 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
         <cylinder length="${bodylen}" radius="${width}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${bodylen/2}"/>
    </collision>
  </link>-->
  
  
  <!--LASER-->
  <link name="base_link">
    <visual>
      <geometry>
		<cylinder length="${radar_w}" radius="${radar_rad}"/>
      <origin rpy="-1.57075 0 0" xyz="0 0 0"/>
      <material name="red"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="red"/>
    </visual>
  </link>
  
</robot>